# Generated by Django 4.1.5 on 2023-01-09 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id_assessment', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('assessment_type', models.CharField(max_length=45)),
                ('date', models.DateTimeField(blank=True, help_text='information about the final submission date of the assessment calculated as the number of days since the start of the module-presentation. The starting date of the presentation has number 0 (zero). weight - weight of the assessment in %. Typically, Exams are treated separately and have the weight100%; the sum of all other assessments is 100%.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_module', models.CharField(max_length=45)),
                ('code_presentation', models.CharField(max_length=45)),
                ('start_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id_student', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(max_length=3)),
                ('region', models.CharField(max_length=45)),
                ('imd_brand', models.CharField(max_length=16)),
                ('highest_education', models.CharField(max_length=45)),
                ('age_band', models.CharField(max_length=16)),
                ('num_of_prev_attempts', models.IntegerField()),
                ('studied_credits', models.IntegerField()),
                ('disability', models.CharField(max_length=3)),
                ('final_result', models.CharField(max_length=45)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='VLE',
            fields=[
                ('id_site', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('activity', models.CharField(max_length=45)),
                ('week_from', models.IntegerField(null=True)),
                ('week_to', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentVle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, help_text='the date of student’s interaction with the material measured as the number of days since the start of the module-presentation.', null=True)),
                ('sum_click', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_vle', to='core.course')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_vle', to='core.vle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_vle', to='core.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registration', models.DateTimeField(auto_now=True)),
                ('date_unregistration', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(blank=True, help_text='the date of student submission, measured as the number of days since the start of the module presentation.', null=True)),
                ('is_banked', models.BooleanField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.studentinfo')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.course'),
        ),
    ]
